### ISSUE TITLE
Team10 Review: Account Activation

### ISSUE THREAD

**Issue by mac-casellaj** [Tamas-Leung/CodeChamp#13]
Most services send new users an account activation email upon account creation that the user is required to access in order for their account to be activated.

In FR.17 it is mentioned that 'The system shall allow users to sign up using a username, email and
password', will this include an account activation email? If not how will CodeChamp defend against bots/programs designed to create large numbers of fake accounts?

**Comment by AntonKanug** [comment]
As google auth is used no extra activation or verification is needed
