### ISSUE TITLE
Team6 Review: Michael Ilao

### ISSUE THREAD

**Issue by michaelilao** [Tamas-Leung/CodeChamp#151]
Very good report and interesting project for Non Functional Req Evaluation for 6.2 evaluating security, after collecting your data from your scenarios what security rating, (since 100% secure cant be achieved) can you give your system and if any are there vulnerabilities not tested.

**Comment by michaelilao** [comment]
@CSchank

**Comment by Tamas-Leung** [comment]
Thanks for the feedback.
