### ISSUE TITLE
Team 06 Review - VnV Report

### ISSUE THREAD

**Issue by Hargun22** [Tamas-Leung/CodeChamp#152]
It is clear that you guys have thoroughly followed the VnV plan and have reflected on the changes made due to testing. One thing that I would've liked to see was an explanation/analysis of the results gathered about the users' preferred language. For example, would you consider adding language support for a language that was preferred by less than 10% of the users? 
Otherwise, well done! Looking forward to your demo at the Expo.

@CSchank

**Comment by Tamas-Leung** [comment]
Thanks for the feedback, Other languages now mentioned in the doc.
