### ISSUE TITLE
Team 06 Review - VnV Report

### ISSUE THREAD

**Issue by EngandDeveloper** [Tamas-Leung/CodeChamp#153]
Amazing project idea. I personally would love to learn and practice DS&A concepts in a fun way :) Great V&V report as well. My only suggestion would be regarding the unit tests. I am glad to hear that you guys are using GitHub Actions to check each PR, our group can perhaps benefit from a similar approach as well. However, I couldn't see anything related to code coverage. Does your unit test suit enough to detect problems or do you guys need to add more tests to increase your confidence in each PR and the system as a whole. 

@CSchank

**Comment by Tamas-Leung** [comment]
Thanks for the feedback!
