### ISSUE TITLE
Team09: IR3 is Restrictive and Unused

### ISSUE THREAD

**Issue by MannyLemos** [Tamas-Leung/CodeChamp#49]
@NickCapstone
Proposed Label for Team 12 to apply to this issue: Review-HazardAnalysis-Team09

IR3 is not cited anywhere in the FMEA table. Moreover, I believe IR3 is extremely restrictive due to how non-specific it is. Will user data never be modified even by the user?

**Comment by YoussefRizkalla** [comment]
Fixed. The requirement was removed as we no longer handle any sensitive user data.
