### ISSUE TITLE
Team 09 Review: FMEA Table

### ISSUE THREAD

**Issue by aaronhsli** [Tamas-Leung/CodeChamp#51]
For your FMEA table, try to connect your "Causes of Failure" and "Recommended Action" using references. For example, for your component "Judge Table", there are 2 "Causes of Failure" for but seems to be only 1 "Recommended Action" with 2 different sections. Splitting up the actions for this one would make it easier to follow (so adding a 1. and 2. to the actions to let someone know which "Cause of Failure" is linked. 

I think the same with the Requirements (IR, AR, etc.) as well. For example, Is both IR4 and AR2 necessary for both of the "Causes of Failure"? 

![image](https://user-images.githubusercontent.com/58313755/197370327-6eb544b1-f9c7-4b30-bf41-9b8059793baf.png)

@nickcapstone

**Comment by Tamas-Leung** [comment]
Fixed
