### ISSUE TITLE
Team8_YichenJiang_VnVReview

### ISSUE THREAD

**Issue by Yichen226** [Tamas-Leung/CodeChamp#56]
- For traceability, system tests cover all of the requirements with enough redundancy to build confidence in the product if the tests all pass; traceability between requirements and test cases is clearly documented. However, some requirements are not covered in the VnV plan. 

- Some of the tests mentioned the product's design, while there are no related documents for the specific design in section "Relevant Documentation."

- Minor grammar and/or spelling errors (some sentences are followed by a dot, but some are not).

**Comment by Tamas-Leung** [comment]
Product design referenced by module guide. All requirements are now traceable. Grammer errors are fixed.
