### ISSUE TITLE
Review-group8 Junhong Chen

### ISSUE THREAD

**Issue by JunhongC-coder** [Tamas-Leung/CodeChamp#57]
Tests need to be more specific and detailed and some tests are not quite related to the corresponding requirements in your traceability table. For example, TC-LF-1 can't test whether or not users spend less than 5 minutes to understand each part of the system. You should test this requriement by collecting information about the time users need to spend on understanding the system

**Comment by Tamas-Leung** [comment]
Test case has been changed and adjusted to be fixed.
