### ISSUE TITLE
Team8_VnVPlan_Review_Tingyu_Shi

### ISSUE THREAD

**Issue by tingyushi** [Tamas-Leung/CodeChamp#58]
Hello Team 12,

1. There are 6 subsets for functional requirements. You may explain how you divided it into 6 subsets.
2. In the traceability matrix, there is only one requirement description for multiple requirements. For example, in the fourth row, there are 8 requirements but only one requirement description. You may add some explanation about this.
3. For the tests of non-functional requirements. Many tests will be conducted by team members. You may invite people outside of your group to do testing.
4. In TC-LF-1, you mentioned that this test will be performed by new users and they will give scores about your system. You may add questionnaires for the testers.
5. For some tests, can be more specific. For example, in TC-P-2, you mentioned "BACKEND_COMPILE_TIME". You may give a specific number about this time. The same problem happens in TC-P-1.

Thanks,
Tingyu Shi

**Comment by YoussefRizkalla** [comment]
- Added - the subsets relate to the major components of the system.
- Added a traceability matrix in addition to the traceability table. The description in the table is for related requirements.
- Added a section on usability testing with user groups.
- Questionnaire was added in the appendix.
- The numbers are mentioned in the appendix as symbolic constants.
